ALTER TABLE "Sindplast"."Perfil"
ADD COLUMN IF NOT EXISTS "DataCadastro" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS "Cadastrante" VARCHAR(100);

ALTER TABLE "Sindplast"."Permissoes"
ADD COLUMN IF NOT EXISTS "DataCadastro" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS "Cadastrante" VARCHAR(100); 